sudo: false

language: go

go:
- 1.11.x
- tip

env:
  GO111MODULE=on

git:
  depth: 1

matrix:
  allow_failures:
  - go: tip
  fast_finish: true

install:
- go get -mod=readonly -v ./...
- go get -u github.com/client9/misspell/cmd/misspell
- go get -u honnef.co/go/tools/cmd/staticcheck@2019.1.1

before_script:
- go vet -tags test
- go mod verify
- misspell -error -locale US *.go
- staticcheck -tags test
- ./.travis.gofmt.sh

script: make test
notifications:
  slack:
    secure: U9cXeQW9YTBp2SNRXKpj8nXP+4ChbssoXD628EMJAnOpV3DTkM4NwfvdJ5StbtIV5nmuZgE8nk+FjlVBSIGNpSaQ8MxOE4SdkOt42uyJGcKISr7U/pkBmVoOFR+mnh6jTGbnSJOhxRCgCEmlcXELrKj+OPMgvoPPTvnGAQAao0Xm7s0hAwzV1r9s0f8e5RZKv5rEGKg/VSZMopv5jFylcQcjRLt4jW4cvwa9TOC374q8AZZck598LtgO93PQRSANX5LTGGTE8rpJDr+yafEQiqSMB8Xh7copXeBGcj5w0lwo1yWmsS5dp3E1QtUVGnJTXIi6xhQ6CI/hgR039y3Q0Mvfiemnt+dP8jJCzhgLDyGrh2DSaURIhc2VprrqymICe4pGAw2Zxz/tyy2U16J465nGDini4JEB8VapJN8zXTxpC/i17RuMjsNjnVeVLkiXw5PnXn2bvyFgLaehtb6Hx+cK/44z9UImWyyJMAxwHnHVkMRq2w3FNaILJsUgI3traiPWUaNutV61VFZViFhdLw12bc6SYYKbkoxWjNw+QvlBBsTOvdbpVqSg9i5veZosHqmXkhBiESsubxcEGcsH5iYPbKYsWemyTspNrcNLfKmkktAA+mxnP4R479e7y98akrsAsFzwV2KyX9ZBaWKxFvWLF88Lvg5laPe7zzSaQmw=
